// Add your dependencies here

dependencies {
    api('com.github.GTNewHorizons:OpenModsLib:0.10.14:dev')

    compileOnly("com.github.GTNewHorizons:Backhand:1.8.13:dev") { transitive = false }
    compileOnly('curse.maven:computercraft-67504:2269339')
    compileOnly('com.github.GTNewHorizons:Mobs-Info:0.5.20-GTNH:dev')
    compileOnly('openperipheral:OpenPeripheralCore-API:3.4.1')

    devOnlyNonPublishable("com.github.GTNewHorizons:AdventureBackpack2:1.4.23-GTNH:dev") { transitive = false }
    devOnlyNonPublishable("com.github.GTNewHorizons:Baubles-Expanded:2.2.22-GTNH:dev") { transitive = false }
    devOnlyNonPublishable("com.github.GTNewHorizons:CosmeticArmorReworked:1.0.6-GTNH:dev") { transitive = false }
    devOnlyNonPublishable("com.github.GTNewHorizons:Galacticraft:3.4.32-GTNH:dev") { transitive = false }
    compileOnly("ganymedes01.etfuturum:Et-Futurum-Requiem:2.6.48-GTNH:dev") { transitive = false }
    devOnlyNonPublishable("com.github.GTNewHorizons:HoloInventory:2.5.16-GTNH:dev") { transitive = false }
    devOnlyNonPublishable("com.github.GTNewHorizons:Minecraft-Backpack-Mod:2.6.16-GTNH:dev") { transitive = false }
    devOnlyNonPublishable('com.github.GTNewHorizons:NotEnoughItems:2.8.121-GTNH:dev')
    devOnlyNonPublishable("com.github.GTNewHorizons:TinkersConstruct:1.14.97-GTNH:dev")
    devOnlyNonPublishable("com.github.GTNewHorizons:waila:1.19.31:dev")
}
